backend:
  name: github
  repo: StarykingTBL/the-daily-algorithm
  branch: main
  auth_type: implicit
  app_id: Ov23lih2FcpzGEUAFncb

media_folder: "public/images/blog"
public_folder: "/images/blog"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title",          name: "title",       widget: "string"                               }
      - { label: "Description",    name: "description", widget: "text"                                 }
      - { label: "Publish Date",   name: "pubDate",     widget: "datetime"                             }
      - { label: "Author",         name: "author",      widget: "string",  default: "The Daily Algorithm" }
      - { label: "Tags",           name: "tags",        widget: "list",    default: []                 }
      - { label: "Featured Image", name: "image",       widget: "image",   required: false             }
      - { label: "Draft",          name: "draft",       widget: "boolean", default: false              }
      - { label: "Body",           name: "body",        widget: "markdown"                             }